name: dart_updater
version: 0.0.3
description: A command line application that updates Dart SDK and Dartium
author: Joel Trottier-Hebert (Pacane) <iamquebecois@gmail.com>
homepage: https://www.stacktrace.ca

environment:
  sdk: '>=1.8.0 <2.0.0'
executables:
  dart_updater:
dependencies:
  dart_config: "^0.5.0"
  archive: "^1.0.20"
  http: "^0.11.3"
  logging: "^0.11.1"
  unscripted: "^0.6.2"
dev_dependencies:
  test: "^0.12.3+8"
