name: dart_updater
version: 0.3.0
description: A command line application that updates Dart SDK
author: Joel Trottier-Hebert (Pacane) <iamquebecois@gmail.com>
homepage: https://github.com/Pacane/dart-updater

environment:
  sdk: '>=1.11.1 <3.0.0'
executables:
  dart_updater:
dependencies:
  analyzer: '^0.27.2'
  archive: '^1.0.20'
  http: "^0.11.3+16"
  logging: '^0.11.2'
  unscripted: '^0.6.2'
dev_dependencies:
  test: '^0.12.13'
